# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Create Release
on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  fetch-depth: 0
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                  type: "zip"
                  path: "./build"
                  filename: "release.zip"
            - name: Upload Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "release.zip"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: "v${{ github.run_id }}"
            # - name: Upload Release
            #   uses: ncipollo/release-action@v1
            #   with:
            #       allowUpdates: true
            #       name: "Automated Release"
            #       commit: "master"
            #       artifacts: "release.zip"
            #       token: ${{ secrets.GITHUB_TOKEN }}
