# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Create Release
on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                  type: "zip"
                  filename: "release.zip"
                  exclusions: "*.git* /*node_modules/* .editorconfig"
            - name: Upload Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "release.zip"
                  token: ${{ secrets.GITHUB_TOKEN }}
